### ISSUE TITLE
Add get command that fetches a upack from a feed

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#42]
It would be great to be able to `get` universal packages as `.upack` file from a feed. Its functionality would provide nice symmetry vs the `push` command.

Use cases:
1. Get a package from a feed to repack it
1. Get a package or edit it locally (manually)
1. Get a package to consume the package itself as content

The third use case is specific for us. We build installers for products that install content that is located in our content package feed. Our installer is universal pack aware and we would like our build scripts to be able to fetch content upacks and place them in the output directory.

**Comment by apapadimoulis** [comment]
Oh, good point; actually I could have used this too, because I had a powershell script that does it.

Though, I'm not a fan of `get`. I'm not sure why. 

On one hand I want to say `pull` , but I wonder if `download` is better; I guess the idea is that this would *not* register as an installation on ProGet server. It's just like the UI.

**Comment by wldevries** [comment]
`download` makes sense to me. `get` would match better with `put` or `post`.

I'm not too concerned with statistics on the server, but I follow your reasoning; The general use case would not be to install it.

**Comment by apapadimoulis** [comment]
@gdivis  thoughts on this?

**Comment by gdivis** [comment]
Sounds good to me. I prefer `get` only because it is shorter :)
